# encoding: utf-8
import requests
from bs4 import BeautifulSoup
'''
	https://suqian.58.com/sale.shtml?utm_source=link&spm=s-41968205011985-pe-f-801.psy_startpage_site&PGTID=0d400024-0763-21ff-cc07-aeebaba5f955&ClickID=5
'''
start_url = 'https://shanghai.58.com/sale.shtml'
url_host = 'http://shanghai.58.com'

def get_channel_urls(start_url):
    web_html = requests.get(start_url)
    soup = BeautifulSoup(web_html.text, 'lxml')
    links = soup.select('ul.ym-submnu > li > b > a')

    for link in links:
        page_url = url_host + link.get('href')
        print(page_url)

channel_list = '''
    http://shanghai.58.com/shouji/
    http://shanghai.58.com/tongxunyw/
    http://shanghai.58.com/danche/
    http://shanghai.58.com/diandongche/
    http://shanghai.58.com/fzixingche/
    http://shanghai.58.com/sanlunche/
    http://shanghai.58.com/peijianzhuangbei/
    http://shanghai.58.com/diannao/
    http://shanghai.58.com/bijiben/
    http://shanghai.58.com/pbdn/
    http://shanghai.58.com/diannaopeijian/
    http://shanghai.58.com/zhoubianshebei/
    http://shanghai.58.com/shuma/
    http://shanghai.58.com/shumaxiangji/
    http://shanghai.58.com/mpsanmpsi/
    http://shanghai.58.com/youxiji/
    http://shanghai.58.com/ershoukongtiao/
    http://suqian.58.com/dianshiji/
    http://suqian.58.com/xiyiji/
    http://suqian.58.com/bingxiang/
    http://suqian.58.com/jiadian/
    http://suqian.58.com/binggui/
    http://suqian.58.com/chuang/
    http://suqian.58.com/ershoujiaju/
    http://suqian.58.com/yingyou/
    http://suqian.58.com/yingeryongpin/
    http://suqian.58.com/muyingweiyang/
    http://suqian.58.com/muyingtongchuang/
    http://suqian.58.com/yunfuyongpin/
    http://suqian.58.com/fushi/
    http://suqian.58.com/nanzhuang/
    http://suqian.58.com/fsxiemao/
    http://suqian.58.com/xiangbao/
    http://suqian.58.com/meirong/
    http://suqian.58.com/yishu/
    http://suqian.58.com/shufahuihua/
    http://suqian.58.com/zhubaoshipin/
    http://suqian.58.com/yuqi/
    http://suqian.58.com/tushu/
    http://suqian.58.com/tushubook/
    http://suqian.58.com/wenti/
    http://suqian.58.com/yundongfushi/
    http://suqian.58.com/jianshenqixie/
    http://suqian.58.com/huju/
    http://suqian.58.com/qiulei/
    http://suqian.58.com/yueqi/
    http://suqian.58.com/kaquan/
    http://suqian.58.com/bangongshebei/
    http://suqian.58.com/diannaohaocai/
    http://suqian.58.com/bangongjiaju/
    http://suqian.58.com/ershoushebei/
    http://suqian.58.com/chengren/
    http://suqian.58.com/nvyongpin/
    http://suqian.58.com/qinglvqingqu/
    http://suqian.58.com/qingquneiyi/
    http://suqian.58.com/chengren/
    http://suqian.58.com/xiaoyuan/
    http://suqian.58.com/ershouqiugou/
    http://suqian.58.com/tiaozao/
    http://shanghai.58.com/shouji/
    http://shanghai.58.com/tongxunyw/
    http://shanghai.58.com/danche/
    http://shanghai.58.com/diandongche/
    http://shanghai.58.com/fzixingche/
    http://shanghai.58.com/sanlunche/
    http://shanghai.58.com/peijianzhuangbei/
    http://shanghai.58.com/diannao/
    http://shanghai.58.com/bijiben/
    http://shanghai.58.com/pbdn/
    http://shanghai.58.com/diannaopeijian/
    http://shanghai.58.com/zhoubianshebei/
    http://shanghai.58.com/shuma/
    http://shanghai.58.com/shumaxiangji/
    http://shanghai.58.com/mpsanmpsi/
    http://shanghai.58.com/youxiji/
    http://shanghai.58.com/ershoukongtiao/
    http://shanghai.58.com/dianshiji/
    http://shanghai.58.com/xiyiji/
    http://shanghai.58.com/bingxiang/
    http://shanghai.58.com/jiadian/
    http://shanghai.58.com/binggui/
    http://shanghai.58.com/chuang/
    http://shanghai.58.com/ershoujiaju/
    http://shanghai.58.com/yingyou/
    http://shanghai.58.com/yingeryongpin/
    http://shanghai.58.com/muyingweiyang/
    http://shanghai.58.com/muyingtongchuang/
    http://shanghai.58.com/yunfuyongpin/
    http://shanghai.58.com/fushi/
    http://shanghai.58.com/nanzhuang/
    http://shanghai.58.com/fsxiemao/
    http://shanghai.58.com/xiangbao/
    http://shanghai.58.com/meirong/
    http://shanghai.58.com/yishu/
    http://shanghai.58.com/shufahuihua/
    http://shanghai.58.com/zhubaoshipin/
    http://shanghai.58.com/yuqi/
    http://shanghai.58.com/tushu/
    http://shanghai.58.com/tushubook/
    http://shanghai.58.com/wenti/
    http://shanghai.58.com/yundongfushi/
    http://shanghai.58.com/jianshenqixie/
    http://shanghai.58.com/huju/
    http://shanghai.58.com/qiulei/
    http://shanghai.58.com/yueqi/
    http://shanghai.58.com/kaquan/
    http://shanghai.58.com/bangongshebei/
    http://shanghai.58.com/diannaohaocai/
    http://shanghai.58.com/bangongjiaju/
    http://shanghai.58.com/ershoushebei/
    http://shanghai.58.com/chengren/
    http://shanghai.58.com/nvyongpin/
    http://shanghai.58.com/qinglvqingqu/
    http://shanghai.58.com/qingquneiyi/
    http://shanghai.58.com/chengren/
    http://shanghai.58.com/xiaoyuan/
    http://shanghai.58.com/ershouqiugou/
    http://shanghai.58.com/tiaozao/
    http://shanghai.58.com/tiaozao/
    http://shanghai.58.com/tiaozao/
    http://chongqing.58.com/shouji/
    http://chongqing.58.com/tongxunyw/
    http://chongqing.58.com/danche/
    http://chongqing.58.com/diandongche/
    http://chongqing.58.com/fzixingche/
    http://chongqing.58.com/sanlunche/
    http://chongqing.58.com/peijianzhuangbei/
    http://chongqing.58.com/diannao/
    http://chongqing.58.com/bijiben/
    http://chongqing.58.com/pbdn/
    http://chongqing.58.com/diannaopeijian/
    http://chongqing.58.com/zhoubianshebei/
    http://chongqing.58.com/shuma/
    http://chongqing.58.com/shumaxiangji/
    http://chongqing.58.com/mpsanmpsi/
    http://chongqing.58.com/youxiji/
    http://chongqing.58.com/ershoukongtiao/
    http://chongqing.58.com/dianshiji/
    http://chongqing.58.com/xiyiji/
    http://chongqing.58.com/bingxiang/
    http://chongqing.58.com/jiadian/
    http://chongqing.58.com/binggui/
    http://chongqing.58.com/chuang/
    http://chongqing.58.com/ershoujiaju/
    http://chongqing.58.com/yingyou/
    http://chongqing.58.com/yingeryongpin/
    http://chongqing.58.com/muyingweiyang/
    http://chongqing.58.com/muyingtongchuang/
    http://chongqing.58.com/yunfuyongpin/
    http://chongqing.58.com/fushi/
    http://chongqing.58.com/nanzhuang/
    http://chongqing.58.com/fsxiemao/
    http://chongqing.58.com/xiangbao/
    http://chongqing.58.com/meirong/
    http://chongqing.58.com/yishu/
    http://chongqing.58.com/shufahuihua/
    http://chongqing.58.com/zhubaoshipin/
    http://chongqing.58.com/yuqi/
    http://chongqing.58.com/tushu/
    http://chongqing.58.com/tushubook/
    http://chongqing.58.com/wenti/
    http://chongqing.58.com/yundongfushi/
    http://chongqing.58.com/jianshenqixie/
    http://chongqing.58.com/huju/
    http://chongqing.58.com/qiulei/
    http://chongqing.58.com/yueqi/
    http://chongqing.58.com/kaquan/
    http://chongqing.58.com/bangongshebei/
    http://chongqing.58.com/diannaohaocai/
    http://chongqing.58.com/bangongjiaju/
    http://chongqing.58.com/ershoushebei/
    http://chongqing.58.com/chengren/
    http://chongqing.58.com/nvyongpin/
    http://chongqing.58.com/qinglvqingqu/
    http://chongqing.58.com/qingquneiyi/
    http://chongqing.58.com/chengren/
    http://chongqing.58.com/xiaoyuan/
    http://chongqing.58.com/ershouqiugou/
    http://chongqing.58.com/tiaozao/
    http://chongqing.58.com/tiaozao/
    http://chongqing.58.com/tiaozao/

'''
if __name__ == '__main__':
    get_channel_urls(start_url)
